# Generated by Django 2.2.6 on 2019-10-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_of_user',
            field=models.CharField(choices=[('builder', 'builder'), ('dealer', 'dealer'), ('owner', 'owner')], max_length=20),
        ),
    ]
