# Generated by Django 2.2.6 on 2019-10-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191012_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccounts',
            name='site',
            field=models.CharField(choices=[('olx', 'olx'), ('bricks', 'bricks')], default='bricks', max_length=20),
            preserve_default=False,
        ),
    ]
